Added spacing variable to conventions
AanZee/styleguides pull request #13
Opened 2017-11-20 16:19 UTC by romypetitjean

2017-11-22 15:05 UTC, michaelmaat commented
Good start, but could you maybe also provide an example of a case  where you would add or substract a given amount of pixels (the -2px example)?

Maybe also add an example where you split a value in two calculations:
margin: ($spacing *2) + ($spacing * 4); //explanation where 2 values come from.

2017-11-30 17:00 UTC, edgargressie requested changes
Agree with @michaelmaat. And maybe add some example calculations with other measure variables. Like `($spacing * x) - $sidebar-width` for example. It may be a good idea to emphasize the spaces between the spacing values too. 😄

2017-12-18 17:22 UTC, edgargressie approved these changes

2018-01-09 14:07 UTC, michaelmaat approved these changes

2018-01-15 15:59 UTC, merged