Feature/editorconfig file
AanZee/styleguides pull request #15
Opened 2017-11-24 09:28 UTC by michaelmaat

Added .editorconfig file and explanation. Using editorconfig should prevent commits that include changes in whitespace, end of line etc.

2017-11-30 16:41 UTC, edgargressie requested changes

2017-11-30 16:41 UTC, edgargressie commented on general/README.md
> +### Use .editorconfig
This should be a double hash

2017-11-30 16:41 UTC, edgargressie commented on general/README.md
>  ### Indents should be done with tabs instead of spaces
Not part of your proposal, but this should be a double hash too.

2017-11-30 20:35 UTC, bartvandebiezen commented
👍

2017-12-06 08:16 UTC, edgargressie approved these changes

2017-12-18 16:19 UTC, merged