Close self-closing tags
AanZee/styleguides pull request #23
Opened 2018-02-26 16:49 UTC by AlexAtSea

2018-02-26 17:09 UTC, AlexAtSea commented
Ik ga nog wat comments toevoegen met een technische reden om dit in te voeren als conventie

2018-02-26 18:23 UTC, bartvandebiezen approved these changes

2018-02-26 18:51 UTC, edgargressie approved these changes

2018-02-26 19:05 UTC, michaelmaat approved these changes

2018-02-27 08:52 UTC, stevengunneweg requested changes

2018-02-27 08:52 UTC, stevengunneweg commented on coldfusion/README.md
> +	<cfset classNames="component component--modifier">
This example should also comply with the 'close self-closing tags' convention below

2018-03-13 07:49 UTC, stevengunneweg approved these changes

2018-03-26 14:53 UTC, merged