[CONV-43] API best practices
AanZee/styleguides pull request #32
Opened 2018-03-12 15:49 UTC by kacperk83

2018-03-12 16:26 UTC, stevengunneweg commented
All conventions are written in English, this one should be too to keep the conventions uniform

2018-03-12 16:33 UTC, kacperk83 commented
@stevengunneweg You are absolutely right. Will fix that (the text has been from Confluence).

2018-03-29 08:36 UTC, stevengunneweg requested changes

2018-03-29 08:36 UTC, stevengunneweg commented on php/api/README.md
> +Wrong:
Please keep right/wrong blocks inline with other conventions/pages

2018-03-29 08:36 UTC, stevengunneweg commented on php/api/README.md
> +GET /v1/products/1?name=
this can be added to the 'better' codeblock above

2018-03-29 08:36 UTC, stevengunneweg commented on php/api/README.md
> +GET /v1/products?client=
this can be added to the 'better' codeblock above

2018-04-05 14:25 UTC, stevengunneweg commented on php/api/README.md
> +Wrong:
Right:
```
<code>
```

Wrong:
```
<code>
```

2018-04-06 07:14 UTC, stevengunneweg approved these changes

2018-04-09 11:36 UTC, edgargressie requested changes
Please have a look at the markdown syntax. When switching to the visual/rendered view you will see some mistakes. The titles, the list beneath 'Ednpoint design' and the strong 'right' and 'wrong' headings for example. See other conventions for the right syntax.

2018-04-09 14:41 UTC, bartvandebiezen commented on api/README.md
> +**Use query parameters for more specific queries**
This is an action/rule. Should be a heading. Don't nest different rules.

2018-04-09 19:40 UTC, closed without merging